config/routes.rb
Rails.application.routes.draw do
  resources :sponsors

  resources :messages

  resources :centers

  resources :children


  post 'twilio/voice' => 'twilio#voice'
  post 'twilio/sms' => 'twilio#message'

  root "application#index"

  # post 'twilio/status' => 'twilio#status'
  post 'notifications/notify' => 'notifications#notify'

  #TODO
  get 'find/sponsors/:sponsor_id', to: 'api#getMessageFromSponsor', as: 'sponsorMessage'
  get 'find/centers/:center_id', to: 'api#getMessageFromCenter', as: 'centerMessage'
  
end

app/models/center.rb
class Center < ActiveRecord::Base
    # attr_accessible :center_id, :location

    has_many :children
    has_many :messages
    
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  before_action :set_center, only: [:show, :edit, :update, :destroy]

  # GET /centers
  # GET /centers.json
  def index
    @centers = Center.all
  end

  # GET /centers/1
  # GET /centers/1.json
  def show
  end

  # GET /centers/new
  def new
    @center = Center.new
  end

  # GET /centers/1/edit
  def edit
  end

  # POST /centers
  # POST /centers.json
  def create
    @center = Center.new(center_params)

    respond_to do |format|
      if @center.save
        format.html { redirect_to @center, notice: 'Center was successfully created.' }
        format.json { render :show, status: :created, location: @center }
      else
        format.html { render :new }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centers/1
  # PATCH/PUT /centers/1.json
  def update
    respond_to do |format|
      if @center.update(center_params)
        format.html { redirect_to @center, notice: 'Center was successfully updated.' }
        format.json { render :show, status: :ok, location: @center }
      else
        format.html { render :edit }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centers/1
  # DELETE /centers/1.json
  def destroy
    @center.destroy
    respond_to do |format|
      format.html { redirect_to centers_url, notice: 'Center was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_center
      @center = Center.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def center_params
      params.require(:center).permit(:center_id, :location)
    end
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/views/centers/_form.html.erb
<%= form_for(@center) do |f| %>
  <% if @center.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@center.errors.count, "error") %> prohibited this center from being saved:</h2>

      <ul>
      <% @center.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :center_id %><br>
    <%= f.number_field :center_id %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/centers/edit.html.erb
<body style="
    text-align: center;
    background-color: white;
    background-image:url(http://www.youngfam.co/wp-content/uploads/2012/10/children-globe-top.jpg);
    background-repeat: no-repeat;
    background-position: absolute;
    ">

	<h1 style="
	      display: block; 
	      font-size: 2em; 
	      text-align: center; 
	      font-family: helvetica;
	      text-decoration: underline;
	      color: #00BFFF;">Editing Center</h1>

</body>

<%= render 'form' %>

<%= link_to 'Show', @center %> |
<%= link_to 'Back', centers_path %>

app/views/centers/index.html.erb
<p id="notice"><%= notice %></p>

<body style="
    text-align: center;
    background-color: white;
    background-image:url(http://www.youngfam.co/wp-content/uploads/2012/10/children-globe-top.jpg);
    background-repeat: no-repeat;
    background-position: absolute;
    ">
  <h1 style="
      display: block; 
      font-size: 3em; 
      text-align: center; 
      font-family: helvetica;
      text-decoration: underline;
      color: #00BFFF;">Listing Centers</h1>

  <table style="
      margin: 0 auto;
      font-size: 1.3em;
      font-family: helvetica;">
    <thead>
      <tr>
        <th>Center</th>
        <th>Location</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @centers.each do |center| %>
        <tr>
          <td><%= center.center_id %></td>
          <td><%= center.location %></td>
          <td><%= link_to 'Show', center %></td>
          <td><%= link_to 'Edit', edit_center_path(center) %></td>
          <td><%= link_to 'Destroy', center, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</body>

<br>

<%= link_to 'New Center', new_center_path %>

app/views/centers/new.html.erb
<body style="
    text-align: center;
    background-color: white;
    background-image:url(http://www.youngfam.co/wp-content/uploads/2012/10/children-globe-top.jpg);
    background-repeat: no-repeat;
    background-position: absolute;
    ">

	<h1 style="
	      display: block; 
	      font-size: 2em; 
	      text-align: center; 
	      font-family: helvetica;
	      text-decoration: underline;
	      color: #00BFFF;">New Center</h1>

</body>

<%= render 'form' %>

<%= link_to 'Back', centers_path %>

app/views/centers/show.html.erb
<p id="notice"><%= notice %></p>

<body style="
    text-align: center;
    background-color: white;
    background-image:url(http://www.youngfam.co/wp-content/uploads/2012/10/children-globe-top.jpg);
    background-repeat: no-repeat;
    background-position: right;
    ">
	<p>
	  <strong>Center:</strong>
	  <%= @center.center_id %>
	</p>

	<p>
	  <strong>Location:</strong>
	  <%= @center.location %>
	</p>

</body>

<%= link_to 'Edit', edit_center_path(@center) %> |
<%= link_to 'Back', centers_path %>