config/routes.rb
Rails.application.routes.draw do
  resources :sponsors

  resources :messages

  resources :centers

  resources :children


  post 'twilio/voice' => 'twilio#voice'
  post 'twilio/sms' => 'twilio#message'

  root "application#index"

  # post 'twilio/status' => 'twilio#status'
  post 'notifications/notify' => 'notifications#notify'

  #TODO
  get 'find/sponsors/:sponsor_id', to: 'api#getMessageFromSponsor', as: 'sponsorMessage'
  get 'find/centers/:center_id', to: 'api#getMessageFromCenter', as: 'centerMessage'
  
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
    # attr_accessible :sponsor_id, :name, :location

    # has_many :messages through: :children
    has_many :children
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :set_sponsor, only: [:show, :edit, :update, :destroy]

  # GET /sponsors
  # GET /sponsors.json
  def index
    @sponsors = Sponsor.all
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
  end

  # GET /sponsors/new
  def new
    @sponsor = Sponsor.new
  end

  # GET /sponsors/1/edit
  def edit
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(sponsor_params)

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render :show, status: :created, location: @sponsor }
      else
        format.html { render :new }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sponsors/1
  # PATCH/PUT /sponsors/1.json
  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sponsor }
      else
        format.html { render :edit }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor.destroy
    respond_to do |format|
      format.html { redirect_to sponsors_url, notice: 'Sponsor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sponsor_params
      params.require(:sponsor).permit(:sponsor_id, :name, :location, :child_id)
    end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.erb
<%= form_for(@sponsor) do |f| %>
  <% if @sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
      <% @sponsor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sponsor_id %><br>
    <%= f.number_field :sponsor_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :child_id %><br>
    <%= f.number_field :child_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sponsors/edit.html.erb
<h1>Editing Sponsor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sponsor %> |
<%= link_to 'Back', sponsors_path %>

app/views/sponsors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sponsors</h1>

<table>
  <thead>
    <tr>
      <th>Sponsor</th>
      <th>Name</th>
      <th>Location</th>
      <th>Child</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sponsors.each do |sponsor| %>
      <tr>
        <td><%= sponsor.sponsor_id %></td>
        <td><%= sponsor.name %></td>
        <td><%= sponsor.location %></td>
        <td><%= sponsor.child_id %></td>
        <td><%= link_to 'Show', sponsor %></td>
        <td><%= link_to 'Edit', edit_sponsor_path(sponsor) %></td>
        <td><%= link_to 'Destroy', sponsor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sponsor', new_sponsor_path %>

app/views/sponsors/new.html.erb
<h1>New Sponsor</h1>

<%= render 'form' %>

<%= link_to 'Back', sponsors_path %>

app/views/sponsors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sponsor:</strong>
  <%= @sponsor.sponsor_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @sponsor.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @sponsor.location %>
</p>

<p>
  <strong>Child:</strong>
  <%= @sponsor.child_id %>
</p>

<%= link_to 'Edit', edit_sponsor_path(@sponsor) %> |
<%= link_to 'Back', sponsors_path %>